REM Recommendation: Place this file in source control.
REM Auto-generated by `./dk dksdk.project.new` of SquirrelScout.

REM Do not let change of directory or other environment vars to spill out of this script
setlocal

REM Change to project directory (this script's parent dir)
cd "%~dp0.."

REM Install Debian GNU/Linux into WSL2
wsl --install -d Debian --no-launch

REM Install compilers and other compilation tools
wsl -d Debian sh -c 'if [ ! -x /usr/bin/gcc ]; then sudo apt-get -q install --no-install-suggests -y build-essential gcc-multilib g++-multilib; fi'

REM Writable /opt/diskuv/usr/share directory for builds
wsl -d Debian sh -c 'if [ ! -w /opt/diskuv/usr/share ]; then sudo install -d /opt/diskuv/usr/share; sudo chown $USER /opt/diskuv/usr/share; fi'
