// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: schema.capnp

package com.example.squirrelscout.data.capnp;

public final class Schema {
  public static class RawMatchData {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)4,(short)4);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return RawMatchData.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final short getTeamNumber() {
        return _getShortField(0);
      }
      public final void setTeamNumber(short value) {
        _setShortField(0, value);
      }

      public final boolean hasTeamName() {
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.Text.Builder getTeamName() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }
      public final void setTeamName(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 0, value);
      }
      public final void setTeamName(String value) {
        _setPointerField(org.capnproto.Text.factory, 0, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initTeamName(int size) {
        return _initPointerField(org.capnproto.Text.factory, 0, size);
      }
      public final short getMatchNumber() {
        return _getShortField(1);
      }
      public final void setMatchNumber(short value) {
        _setShortField(1, value);
      }

      public final boolean hasScouterName() {
        return !_pointerFieldIsNull(1);
      }
      public final org.capnproto.Text.Builder getScouterName() {
        return _getPointerField(org.capnproto.Text.factory, 1, null, 0, 0);
      }
      public final void setScouterName(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 1, value);
      }
      public final void setScouterName(String value) {
        _setPointerField(org.capnproto.Text.factory, 1, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initScouterName(int size) {
        return _initPointerField(org.capnproto.Text.factory, 1, size);
      }
      public final com.example.squirrelscout.data.capnp.Schema.RobotPosition getAllianceColor() {
        switch(_getShortField(2)) {
          case 0 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.RED1;
          case 1 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.RED2;
          case 2 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.RED3;
          case 3 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.BLUE1;
          case 4 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.BLUE2;
          case 5 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.BLUE3;
          default: return com.example.squirrelscout.data.capnp.Schema.RobotPosition._NOT_IN_SCHEMA;
        }
      }
      public final void setAllianceColor(com.example.squirrelscout.data.capnp.Schema.RobotPosition value) {
        _setShortField(2, (short)value.ordinal());
      }

      public final com.example.squirrelscout.data.capnp.Schema.SPosition getStartingPosition() {
        switch(_getShortField(3)) {
          case 0 : return com.example.squirrelscout.data.capnp.Schema.SPosition.AMP_SIDE;
          case 1 : return com.example.squirrelscout.data.capnp.Schema.SPosition.CENTER;
          case 2 : return com.example.squirrelscout.data.capnp.Schema.SPosition.SOURCE_SIDE;
          default: return com.example.squirrelscout.data.capnp.Schema.SPosition._NOT_IN_SCHEMA;
        }
      }
      public final void setStartingPosition(com.example.squirrelscout.data.capnp.Schema.SPosition value) {
        _setShortField(3, (short)value.ordinal());
      }

      public final boolean getWingNote1() {
        return _getBooleanField(64);
      }
      public final void setWingNote1(boolean value) {
        _setBooleanField(64, value);
      }

      public final boolean getWingNote2() {
        return _getBooleanField(65);
      }
      public final void setWingNote2(boolean value) {
        _setBooleanField(65, value);
      }

      public final boolean getWingNote3() {
        return _getBooleanField(66);
      }
      public final void setWingNote3(boolean value) {
        _setBooleanField(66, value);
      }

      public final boolean getCenterNote1() {
        return _getBooleanField(67);
      }
      public final void setCenterNote1(boolean value) {
        _setBooleanField(67, value);
      }

      public final boolean getCenterNote2() {
        return _getBooleanField(68);
      }
      public final void setCenterNote2(boolean value) {
        _setBooleanField(68, value);
      }

      public final boolean getCenterNote3() {
        return _getBooleanField(69);
      }
      public final void setCenterNote3(boolean value) {
        _setBooleanField(69, value);
      }

      public final boolean getCenterNote4() {
        return _getBooleanField(70);
      }
      public final void setCenterNote4(boolean value) {
        _setBooleanField(70, value);
      }

      public final boolean getCenterNote5() {
        return _getBooleanField(71);
      }
      public final void setCenterNote5(boolean value) {
        _setBooleanField(71, value);
      }

      public final short getAutoAmpScore() {
        return _getShortField(5);
      }
      public final void setAutoAmpScore(short value) {
        _setShortField(5, value);
      }

      public final short getAutoAmpMiss() {
        return _getShortField(6);
      }
      public final void setAutoAmpMiss(short value) {
        _setShortField(6, value);
      }

      public final short getAutoSpeakerScore() {
        return _getShortField(7);
      }
      public final void setAutoSpeakerScore(short value) {
        _setShortField(7, value);
      }

      public final short getAutoSpeakerMiss() {
        return _getShortField(8);
      }
      public final void setAutoSpeakerMiss(short value) {
        _setShortField(8, value);
      }

      public final boolean getAutoLeave() {
        return _getBooleanField(72);
      }
      public final void setAutoLeave(boolean value) {
        _setBooleanField(72, value);
      }

      public final short getTeleSpeakerScore() {
        return _getShortField(9);
      }
      public final void setTeleSpeakerScore(short value) {
        _setShortField(9, value);
      }

      public final short getTeleSpeakerMiss() {
        return _getShortField(10);
      }
      public final void setTeleSpeakerMiss(short value) {
        _setShortField(10, value);
      }

      public final short getTeleAmpScore() {
        return _getShortField(11);
      }
      public final void setTeleAmpScore(short value) {
        _setShortField(11, value);
      }

      public final short getTeleAmpMiss() {
        return _getShortField(12);
      }
      public final void setTeleAmpMiss(short value) {
        _setShortField(12, value);
      }

      public final boolean hasDistance() {
        return !_pointerFieldIsNull(2);
      }
      public final org.capnproto.Text.Builder getDistance() {
        return _getPointerField(org.capnproto.Text.factory, 2, null, 0, 0);
      }
      public final void setDistance(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 2, value);
      }
      public final void setDistance(String value) {
        _setPointerField(org.capnproto.Text.factory, 2, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initDistance(int size) {
        return _initPointerField(org.capnproto.Text.factory, 2, size);
      }
      public final com.example.squirrelscout.data.capnp.Schema.TBreakdown getTeleBreakdown() {
        switch(_getShortField(13)) {
          case 0 : return com.example.squirrelscout.data.capnp.Schema.TBreakdown.NONE;
          case 1 : return com.example.squirrelscout.data.capnp.Schema.TBreakdown.TIPPED;
          case 2 : return com.example.squirrelscout.data.capnp.Schema.TBreakdown.MECHANICAL_FAILURE;
          case 3 : return com.example.squirrelscout.data.capnp.Schema.TBreakdown.INCAPACITATED;
          case 4 : return com.example.squirrelscout.data.capnp.Schema.TBreakdown.NOTE_STUCK;
          default: return com.example.squirrelscout.data.capnp.Schema.TBreakdown._NOT_IN_SCHEMA;
        }
      }
      public final void setTeleBreakdown(com.example.squirrelscout.data.capnp.Schema.TBreakdown value) {
        _setShortField(13, (short)value.ordinal());
      }

      public final boolean hasTelePickup() {
        return !_pointerFieldIsNull(3);
      }
      public final org.capnproto.Text.Builder getTelePickup() {
        return _getPointerField(org.capnproto.Text.factory, 3, null, 0, 0);
      }
      public final void setTelePickup(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 3, value);
      }
      public final void setTelePickup(String value) {
        _setPointerField(org.capnproto.Text.factory, 3, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initTelePickup(int size) {
        return _initPointerField(org.capnproto.Text.factory, 3, size);
      }
      public final com.example.squirrelscout.data.capnp.Schema.EClimb getEndgameClimb() {
        switch(_getShortField(14)) {
          case 0 : return com.example.squirrelscout.data.capnp.Schema.EClimb.SUCCESS;
          case 1 : return com.example.squirrelscout.data.capnp.Schema.EClimb.FAILED;
          case 2 : return com.example.squirrelscout.data.capnp.Schema.EClimb.DID_NOT_ATTEMPT;
          case 3 : return com.example.squirrelscout.data.capnp.Schema.EClimb.HARMONY;
          case 4 : return com.example.squirrelscout.data.capnp.Schema.EClimb.PARKED;
          default: return com.example.squirrelscout.data.capnp.Schema.EClimb._NOT_IN_SCHEMA;
        }
      }
      public final void setEndgameClimb(com.example.squirrelscout.data.capnp.Schema.EClimb value) {
        _setShortField(14, (short)value.ordinal());
      }

      public final boolean getEndgameTrap() {
        return _getBooleanField(73);
      }
      public final void setEndgameTrap(boolean value) {
        _setBooleanField(73, value);
      }

    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public final short getTeamNumber() {
        return _getShortField(0);
      }

      public boolean hasTeamName() {
        return !_pointerFieldIsNull(0);
      }
      public org.capnproto.Text.Reader getTeamName() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }

      public final short getMatchNumber() {
        return _getShortField(1);
      }

      public boolean hasScouterName() {
        return !_pointerFieldIsNull(1);
      }
      public org.capnproto.Text.Reader getScouterName() {
        return _getPointerField(org.capnproto.Text.factory, 1, null, 0, 0);
      }

      public final com.example.squirrelscout.data.capnp.Schema.RobotPosition getAllianceColor() {
        switch(_getShortField(2)) {
          case 0 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.RED1;
          case 1 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.RED2;
          case 2 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.RED3;
          case 3 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.BLUE1;
          case 4 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.BLUE2;
          case 5 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.BLUE3;
          default: return com.example.squirrelscout.data.capnp.Schema.RobotPosition._NOT_IN_SCHEMA;
        }
      }

      public final com.example.squirrelscout.data.capnp.Schema.SPosition getStartingPosition() {
        switch(_getShortField(3)) {
          case 0 : return com.example.squirrelscout.data.capnp.Schema.SPosition.AMP_SIDE;
          case 1 : return com.example.squirrelscout.data.capnp.Schema.SPosition.CENTER;
          case 2 : return com.example.squirrelscout.data.capnp.Schema.SPosition.SOURCE_SIDE;
          default: return com.example.squirrelscout.data.capnp.Schema.SPosition._NOT_IN_SCHEMA;
        }
      }

      public final boolean getWingNote1() {
        return _getBooleanField(64);
      }

      public final boolean getWingNote2() {
        return _getBooleanField(65);
      }

      public final boolean getWingNote3() {
        return _getBooleanField(66);
      }

      public final boolean getCenterNote1() {
        return _getBooleanField(67);
      }

      public final boolean getCenterNote2() {
        return _getBooleanField(68);
      }

      public final boolean getCenterNote3() {
        return _getBooleanField(69);
      }

      public final boolean getCenterNote4() {
        return _getBooleanField(70);
      }

      public final boolean getCenterNote5() {
        return _getBooleanField(71);
      }

      public final short getAutoAmpScore() {
        return _getShortField(5);
      }

      public final short getAutoAmpMiss() {
        return _getShortField(6);
      }

      public final short getAutoSpeakerScore() {
        return _getShortField(7);
      }

      public final short getAutoSpeakerMiss() {
        return _getShortField(8);
      }

      public final boolean getAutoLeave() {
        return _getBooleanField(72);
      }

      public final short getTeleSpeakerScore() {
        return _getShortField(9);
      }

      public final short getTeleSpeakerMiss() {
        return _getShortField(10);
      }

      public final short getTeleAmpScore() {
        return _getShortField(11);
      }

      public final short getTeleAmpMiss() {
        return _getShortField(12);
      }

      public boolean hasDistance() {
        return !_pointerFieldIsNull(2);
      }
      public org.capnproto.Text.Reader getDistance() {
        return _getPointerField(org.capnproto.Text.factory, 2, null, 0, 0);
      }

      public final com.example.squirrelscout.data.capnp.Schema.TBreakdown getTeleBreakdown() {
        switch(_getShortField(13)) {
          case 0 : return com.example.squirrelscout.data.capnp.Schema.TBreakdown.NONE;
          case 1 : return com.example.squirrelscout.data.capnp.Schema.TBreakdown.TIPPED;
          case 2 : return com.example.squirrelscout.data.capnp.Schema.TBreakdown.MECHANICAL_FAILURE;
          case 3 : return com.example.squirrelscout.data.capnp.Schema.TBreakdown.INCAPACITATED;
          case 4 : return com.example.squirrelscout.data.capnp.Schema.TBreakdown.NOTE_STUCK;
          default: return com.example.squirrelscout.data.capnp.Schema.TBreakdown._NOT_IN_SCHEMA;
        }
      }

      public boolean hasTelePickup() {
        return !_pointerFieldIsNull(3);
      }
      public org.capnproto.Text.Reader getTelePickup() {
        return _getPointerField(org.capnproto.Text.factory, 3, null, 0, 0);
      }

      public final com.example.squirrelscout.data.capnp.Schema.EClimb getEndgameClimb() {
        switch(_getShortField(14)) {
          case 0 : return com.example.squirrelscout.data.capnp.Schema.EClimb.SUCCESS;
          case 1 : return com.example.squirrelscout.data.capnp.Schema.EClimb.FAILED;
          case 2 : return com.example.squirrelscout.data.capnp.Schema.EClimb.DID_NOT_ATTEMPT;
          case 3 : return com.example.squirrelscout.data.capnp.Schema.EClimb.HARMONY;
          case 4 : return com.example.squirrelscout.data.capnp.Schema.EClimb.PARKED;
          default: return com.example.squirrelscout.data.capnp.Schema.EClimb._NOT_IN_SCHEMA;
        }
      }

      public final boolean getEndgameTrap() {
        return _getBooleanField(73);
      }

    }

  }


  public enum SPosition {
    AMP_SIDE,
    CENTER,
    SOURCE_SIDE,
    _NOT_IN_SCHEMA,
  }

  public enum TBreakdown {
    NONE,
    TIPPED,
    MECHANICAL_FAILURE,
    INCAPACITATED,
    NOTE_STUCK,
    _NOT_IN_SCHEMA,
  }

  public enum EClimb {
    SUCCESS,
    FAILED,
    DID_NOT_ATTEMPT,
    HARMONY,
    PARKED,
    _NOT_IN_SCHEMA,
  }

  public enum RobotPosition {
    RED1,
    RED2,
    RED3,
    BLUE1,
    BLUE2,
    BLUE3,
    _NOT_IN_SCHEMA,
  }

  public static class MatchAndPosition {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)1,(short)0);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return MatchAndPosition.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final short getMatch() {
        return _getShortField(0);
      }
      public final void setMatch(short value) {
        _setShortField(0, value);
      }

      public final com.example.squirrelscout.data.capnp.Schema.RobotPosition getPosition() {
        switch(_getShortField(1)) {
          case 0 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.RED1;
          case 1 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.RED2;
          case 2 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.RED3;
          case 3 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.BLUE1;
          case 4 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.BLUE2;
          case 5 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.BLUE3;
          default: return com.example.squirrelscout.data.capnp.Schema.RobotPosition._NOT_IN_SCHEMA;
        }
      }
      public final void setPosition(com.example.squirrelscout.data.capnp.Schema.RobotPosition value) {
        _setShortField(1, (short)value.ordinal());
      }

    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public final short getMatch() {
        return _getShortField(0);
      }

      public final com.example.squirrelscout.data.capnp.Schema.RobotPosition getPosition() {
        switch(_getShortField(1)) {
          case 0 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.RED1;
          case 1 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.RED2;
          case 2 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.RED3;
          case 3 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.BLUE1;
          case 4 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.BLUE2;
          case 5 : return com.example.squirrelscout.data.capnp.Schema.RobotPosition.BLUE3;
          default: return com.example.squirrelscout.data.capnp.Schema.RobotPosition._NOT_IN_SCHEMA;
        }
      }

    }

  }


  public static class MaybeError {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)1,(short)1);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return MaybeError.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final boolean getSuccess() {
        return _getBooleanField(0);
      }
      public final void setSuccess(boolean value) {
        _setBooleanField(0, value);
      }

      public final boolean hasMessageIfError() {
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.Text.Builder getMessageIfError() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }
      public final void setMessageIfError(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 0, value);
      }
      public final void setMessageIfError(String value) {
        _setPointerField(org.capnproto.Text.factory, 0, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initMessageIfError(int size) {
        return _initPointerField(org.capnproto.Text.factory, 0, size);
      }
    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public final boolean getSuccess() {
        return _getBooleanField(0);
      }

      public boolean hasMessageIfError() {
        return !_pointerFieldIsNull(0);
      }
      public org.capnproto.Text.Reader getMessageIfError() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }

    }

  }



public static final class Schemas {
public static final org.capnproto.SegmentReader b_faef7bb13948ce39 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u0039\u00ce\u0048\u0039\u00b1\u007b\u00ef\u00fa" +
   "\r\u0000\u0000\u0000\u0001\u0000\u0004\u0000" +
   "\u006f\u005a\u004b\u009d\u00a1\u001f\u0004\u00ff" +
   "\u0004\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00d2\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0027\u0006\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0063\u0068\u0065\u006d\u0061\u002e\u0063" +
   "\u0061\u0070\u006e\u0070\u003a\u0052\u0061\u0077" +
   "\u004d\u0061\u0074\u0063\u0068\u0044\u0061\u0074" +
   "\u0061\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0070\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0003\u0000\u0000\u005a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u000c\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0009\u0003\u0000\u0000\u004a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0008\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0014\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0002\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0011\u0003\u0000\u0000\u0062\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u001c\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0003\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0003\u0000\u0000\u0062\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0018\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0024\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0004\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0004\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0021\u0003\u0000\u0000\u0072\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0020\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u002c\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0005\u0000\u0000\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0005\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0029\u0003\u0000\u0000\u008a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u002c\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0038\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0006\u0000\u0000\u0000\u0040\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0006\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0035\u0003\u0000\u0000\u0052\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0034\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0040\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0007\u0000\u0000\u0000\u0041\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u003d\u0003\u0000\u0000\u0052\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u003c\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0048\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0008\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0008\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0045\u0003\u0000\u0000\u0052\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0044\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0050\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0009\u0000\u0000\u0000\u0043\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0009\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u004d\u0003\u0000\u0000\u0062\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u004c\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0058\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\n\u0000\u0000\u0000\u0044\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\n\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0055\u0003\u0000\u0000\u0062\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0054\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0060\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u000b\u0000\u0000\u0000\u0045\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u000b\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u005d\u0003\u0000\u0000\u0062\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\\\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0068\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0046\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u000c\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0065\u0003\u0000\u0000\u0062\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0064\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0070\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\r\u0000\u0000\u0000\u0047\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\r\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u006d\u0003\u0000\u0000\u0062\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u006c\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0078\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u000e\u0000\u0000\u0000\u0005\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u000e\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0075\u0003\u0000\u0000\u006a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0080\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u000f\u0000\u0000\u0000\u0006\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u000f\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u007d\u0003\u0000\u0000\u0062\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u007c\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0088\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0010\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0010\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0085\u0003\u0000\u0000\u008a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0088\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0094\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0011\u0000\u0000\u0000\u0008\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0011\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0091\u0003\u0000\u0000\u0082\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0090\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u009c\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0012\u0000\u0000\u0000\u0048\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0012\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0099\u0003\u0000\u0000\u0052\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0098\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00a4\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0013\u0000\u0000\u0000\u0009\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0013\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00a1\u0003\u0000\u0000\u008a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00a4\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00b0\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0014\u0000\u0000\u0000\n\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0014\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00ad\u0003\u0000\u0000\u0082\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00ac\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00b8\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0015\u0000\u0000\u0000\u000b\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0015\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00b5\u0003\u0000\u0000\u006a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00b4\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00c0\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0016\u0000\u0000\u0000\u000c\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0016\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00bd\u0003\u0000\u0000\u0062\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00bc\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00c8\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0017\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0017\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00c5\u0003\u0000\u0000\u004a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00c4\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00d0\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0018\u0000\u0000\u0000\r\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0018\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00cd\u0003\u0000\u0000\u0072\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00cc\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00d8\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0019\u0000\u0000\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0019\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00d5\u0003\u0000\u0000\u005a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00d4\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00e0\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u001a\u0000\u0000\u0000\u000e\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u001a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00dd\u0003\u0000\u0000\u006a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00dc\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00e8\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u001b\u0000\u0000\u0000\u0049\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u001b\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00e5\u0003\u0000\u0000\u0062\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00e4\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00f0\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0074\u0065\u0061\u006d\u004e\u0075\u006d\u0062" +
   "\u0065\u0072\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0065\u0061\u006d\u004e\u0061\u006d\u0065" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u006d\u0061\u0074\u0063\u0068\u004e\u0075\u006d" +
   "\u0062\u0065\u0072\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0063\u006f\u0075\u0074\u0065\u0072\u004e" +
   "\u0061\u006d\u0065\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u006c\u006c\u0069\u0061\u006e\u0063\u0065" +
   "\u0043\u006f\u006c\u006f\u0072\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0036\u007f\u00d9\u00b5\u0087\u0076\u0096\u00e6" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0074\u0061\u0072\u0074\u0069\u006e\u0067" +
   "\u0050\u006f\u0073\u0069\u0074\u0069\u006f\u006e" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00b9\\\u0010\u00f8\u008c\n\u00b3\u00dd" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0077\u0069\u006e\u0067\u004e\u006f\u0074\u0065" +
   "\u0031\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0077\u0069\u006e\u0067\u004e\u006f\u0074\u0065" +
   "\u0032\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0077\u0069\u006e\u0067\u004e\u006f\u0074\u0065" +
   "\u0033\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0063\u0065\u006e\u0074\u0065\u0072\u004e\u006f" +
   "\u0074\u0065\u0031\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0063\u0065\u006e\u0074\u0065\u0072\u004e\u006f" +
   "\u0074\u0065\u0032\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0063\u0065\u006e\u0074\u0065\u0072\u004e\u006f" +
   "\u0074\u0065\u0033\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0063\u0065\u006e\u0074\u0065\u0072\u004e\u006f" +
   "\u0074\u0065\u0034\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0063\u0065\u006e\u0074\u0065\u0072\u004e\u006f" +
   "\u0074\u0065\u0035\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0075\u0074\u006f\u0041\u006d\u0070\u0053" +
   "\u0063\u006f\u0072\u0065\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0075\u0074\u006f\u0041\u006d\u0070\u004d" +
   "\u0069\u0073\u0073\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0075\u0074\u006f\u0053\u0070\u0065\u0061" +
   "\u006b\u0065\u0072\u0053\u0063\u006f\u0072\u0065" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0075\u0074\u006f\u0053\u0070\u0065\u0061" +
   "\u006b\u0065\u0072\u004d\u0069\u0073\u0073\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0075\u0074\u006f\u004c\u0065\u0061\u0076" +
   "\u0065\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0065\u006c\u0065\u0053\u0070\u0065\u0061" +
   "\u006b\u0065\u0072\u0053\u0063\u006f\u0072\u0065" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0065\u006c\u0065\u0053\u0070\u0065\u0061" +
   "\u006b\u0065\u0072\u004d\u0069\u0073\u0073\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0065\u006c\u0065\u0041\u006d\u0070\u0053" +
   "\u0063\u006f\u0072\u0065\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0065\u006c\u0065\u0041\u006d\u0070\u004d" +
   "\u0069\u0073\u0073\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0064\u0069\u0073\u0074\u0061\u006e\u0063\u0065" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0065\u006c\u0065\u0042\u0072\u0065\u0061" +
   "\u006b\u0064\u006f\u0077\u006e\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u003d\u002a\u0075\u0015\u00f0\u00d2\u00d2\u00e5" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0065\u006c\u0065\u0050\u0069\u0063\u006b" +
   "\u0075\u0070\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0065\u006e\u0064\u0067\u0061\u006d\u0065\u0043" +
   "\u006c\u0069\u006d\u0062\u0000\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0080\u0031\u0048\u00ca\u0009\u0086\u00d0\u00bb" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0065\u006e\u0064\u0067\u0061\u006d\u0065\u0054" +
   "\u0072\u0061\u0070\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_ddb30a8cf8105cb9 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u00b9\\\u0010\u00f8\u008c\n\u00b3\u00dd" +
   "\r\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u006f\u005a\u004b\u009d\u00a1\u001f\u0004\u00ff" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00ba\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u004f\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0063\u0068\u0065\u006d\u0061\u002e\u0063" +
   "\u0061\u0070\u006e\u0070\u003a\u0053\u0050\u006f" +
   "\u0073\u0069\u0074\u0069\u006f\u006e\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\r\u0000\u0000\u0000\u005a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u006d\u0070\u0053\u0069\u0064\u0065\u0000" +
   "\u0063\u0065\u006e\u0074\u0065\u0072\u0000\u0000" +
   "\u0073\u006f\u0075\u0072\u0063\u0065\u0053\u0069" +
   "\u0064\u0065\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_e5d2d2f015752a3d =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u003d\u002a\u0075\u0015\u00f0\u00d2\u00d2\u00e5" +
   "\r\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u006f\u005a\u004b\u009d\u00a1\u001f\u0004\u00ff" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00c2\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u007f\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0063\u0068\u0065\u006d\u0061\u002e\u0063" +
   "\u0061\u0070\u006e\u0070\u003a\u0054\u0042\u0072" +
   "\u0065\u0061\u006b\u0064\u006f\u0077\u006e\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0014\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0035\u0000\u0000\u0000\u002a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u002d\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0025\u0000\u0000\u0000\u0092\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0025\u0000\u0000\u0000\u0072\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0052\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u006e\u006f\u006e\u0065\u0000\u0000\u0000\u0000" +
   "\u0074\u0069\u0070\u0070\u0065\u0064\u0000\u0000" +
   "\u006d\u0065\u0063\u0068\u0061\u006e\u0069\u0063" +
   "\u0061\u006c\u0046\u0061\u0069\u006c\u0075\u0072" +
   "\u0065\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0069\u006e\u0063\u0061\u0070\u0061\u0063\u0069" +
   "\u0074\u0061\u0074\u0065\u0064\u0000\u0000\u0000" +
   "\u006e\u006f\u0074\u0065\u0053\u0074\u0075\u0063" +
   "\u006b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_bbd08609ca483180 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u0080\u0031\u0048\u00ca\u0009\u0086\u00d0\u00bb" +
   "\r\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u006f\u005a\u004b\u009d\u00a1\u001f\u0004\u00ff" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00a2\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u007f\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0063\u0068\u0065\u006d\u0061\u002e\u0063" +
   "\u0061\u0070\u006e\u0070\u003a\u0045\u0043\u006c" +
   "\u0069\u006d\u0062\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0014\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0035\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u002d\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0025\u0000\u0000\u0000\u0072\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0075\u0063\u0063\u0065\u0073\u0073\u0000" +
   "\u0066\u0061\u0069\u006c\u0065\u0064\u0000\u0000" +
   "\u0064\u0069\u0064\u004e\u006f\u0074\u0041\u0074" +
   "\u0074\u0065\u006d\u0070\u0074\u0000\u0000\u0000" +
   "\u0068\u0061\u0072\u006d\u006f\u006e\u0079\u0000" +
   "\u0070\u0061\u0072\u006b\u0065\u0064\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_e6967687b5d97f36 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u0036\u007f\u00d9\u00b5\u0087\u0076\u0096\u00e6" +
   "\r\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u006f\u005a\u004b\u009d\u00a1\u001f\u0004\u00ff" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00da\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0097\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0063\u0068\u0065\u006d\u0061\u002e\u0063" +
   "\u0061\u0070\u006e\u0070\u003a\u0052\u006f\u0062" +
   "\u006f\u0074\u0050\u006f\u0073\u0069\u0074\u0069" +
   "\u006f\u006e\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0018\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0041\u0000\u0000\u0000\u002a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0039\u0000\u0000\u0000\u002a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0031\u0000\u0000\u0000\u002a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0029\u0000\u0000\u0000\u0032\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0032\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0005\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u0032\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0072\u0065\u0064\u0031\u0000\u0000\u0000\u0000" +
   "\u0072\u0065\u0064\u0032\u0000\u0000\u0000\u0000" +
   "\u0072\u0065\u0064\u0033\u0000\u0000\u0000\u0000" +
   "\u0062\u006c\u0075\u0065\u0031\u0000\u0000\u0000" +
   "\u0062\u006c\u0075\u0065\u0032\u0000\u0000\u0000" +
   "\u0062\u006c\u0075\u0065\u0033\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_fcb71e38a70d3910 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u0010\u0039\r\u00a7\u0038\u001e\u00b7\u00fc" +
   "\r\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u006f\u005a\u004b\u009d\u00a1\u001f\u0004\u00ff" +
   "\u0000\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00f2\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0077\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0063\u0068\u0065\u006d\u0061\u002e\u0063" +
   "\u0061\u0070\u006e\u0070\u003a\u004d\u0061\u0074" +
   "\u0063\u0068\u0041\u006e\u0064\u0050\u006f\u0073" +
   "\u0069\u0074\u0069\u006f\u006e\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0008\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0029\u0000\u0000\u0000\u0032\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0024\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0030\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u002d\u0000\u0000\u0000\u004a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u002c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0038\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u006d\u0061\u0074\u0063\u0068\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0070\u006f\u0073\u0069\u0074\u0069\u006f\u006e" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0036\u007f\u00d9\u00b5\u0087\u0076\u0096\u00e6" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_db6aa7ecdb8f85bb =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u00bb\u0085\u008f\u00db\u00ec\u00a7\u006a\u00db" +
   "\r\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u006f\u005a\u004b\u009d\u00a1\u001f\u0004\u00ff" +
   "\u0001\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00c2\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u0077\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0063\u0068\u0065\u006d\u0061\u002e\u0063" +
   "\u0061\u0070\u006e\u0070\u003a\u004d\u0061\u0079" +
   "\u0062\u0065\u0045\u0072\u0072\u006f\u0072\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0008\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0029\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0024\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0030\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u002d\u0000\u0000\u0000\u007a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u002c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0038\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0073\u0075\u0063\u0063\u0065\u0073\u0073\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u006d\u0065\u0073\u0073\u0061\u0067\u0065\u0049" +
   "\u0066\u0045\u0072\u0072\u006f\u0072\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
}
}

